### ISSUE TITLE
Revit 2019 crashes when using 3D rotate tool

### ISSUE THREAD

**Issue by AndersB92** [CyrilWaechter/pyRevitMEP#10]
![image](https://user-images.githubusercontent.com/47623505/52768563-280bc680-302e-11e9-8ede-1a9bbb7f806c.png)

Here's what my window looks like, and what I was trying to do. Wanted to rotate the angular fitting part with the attached duct selected. Have tried rebooting the PC after the installation, but the error persist. Am I using this tool wrong?

I just installed pyRevit and installed pyRevitMEP automatic through the pyRevit Extension Manager, so I should have the newest version.

**Comment by CyrilWaechter** [comment]
Hi,

I see that you have Revit 2019 and not Revit 2019.2 installed. Can you please try to update to 2019.2 ?

I updated pyRevit to last version and tested the tool it still works for me. I am currently unable to reproduce the bug you show.
* pyRevit 4.6.15
* Revit 2019.2

If it doesn't solve your issue. Unfortunately, these bugs related to non modal windows are very hard to debug as there is no stacktrace (explicit error message saying where error occur in the code).
Did you watch the [tutorial video](https://www.youtube.com/watch?v=60Y_DJbIL5Y&t=2s) which show how to use this tool ?
If yes, do you use it this way ? Can you explain step by step what you do and/or make a short video showing how error occurs (with [OBS Studio](https://obsproject.com/) for example).

**Comment by AndersB92** [comment]
Hi!

Yes, I was trying to replicate the proces from the video tutorial. The steps I take are as follows (I'll see about making a video of the steps, but I'll explain the steps first):

Step 1: Selecting both the angle and the attached duct (those selected in the screenprint)
Step 2: Click the "3D rotate"-tool, enter "45" into the "Rotate around the selected axis", and click the button below "Select axis and rotate". The angle and duct part is still marked/selected.
Step 3: Now, I should be able to select the other duct part, which the angle fitting is connected to (the duct part wich wasn't selected through step 1), as my rotating axis... however, this is where things crashes.

I'll see about updating Revit to the latest version (2019.2), and try again, and let you know if things changes. It's a very cool feature though, and I'd really love to make it work :-)

**Comment by CyrilWaechter** [comment]
Any update ? Did 2019.2 solved the issue ?

**Comment by AndersB92** [comment]
No, sorry. Haven't updated yet - tried it on Revit 18.1 and the same error occured though.. It might take awhile before I get to update Revit to 19.2 and try it.

**Comment by AndersB92** [comment]
Okay - I've updated to Revit 19.2 now, and the error seems still to occur. Perhaps I need to reinstall Revit?
This is what I do:
![image](https://user-images.githubusercontent.com/47623505/53172687-405b8280-35e6-11e9-8c55-4d12e861742b.png)
- I click the "3D rotate" tool
![image](https://user-images.githubusercontent.com/47623505/53172755-68e37c80-35e6-11e9-8d89-fe68efe87211.png)
- I then select the part I want to rotate
![image](https://user-images.githubusercontent.com/47623505/53172811-89133b80-35e6-11e9-9cde-2e07efbe0d44.png)
- I insert 45° into the "Rotation angle", click "Select axis and rotate" and then...
![image](https://user-images.githubusercontent.com/47623505/53172950-e3ac9780-35e6-11e9-9662-3ff8f8f4e17a.png)

**Comment by CyrilWaechter** [comment]
Mmh… Strange…

1. Did you try to use the function in an empty project with Revit default mechanical template ?
2. Did you try to use another modeless tool like Rename (to rename views), Change Level (to change reference level of objects) ? If not please try and tell me if it works.
3. The message error also is different from what I thought. Usually when it crashs with modeless events it is mercyless you cannot even save a recovery file.

If you already tried with 2018.1 I don't think reinstalling Revit would change this. However I see that you have many addins. Can you please also try to deactivate all addins except pyRevit. You can rename following folder temporarily and make sure that pyRevit.addin is in one of these folder (not the renamed ones) : 
`%ProgramData%\Autodesk\Revit\Addins\2019`
`%AppData%\Roaming\Autodesk\Revit\Addins\2019`
The last addin which made a mess was one from Autodesk… (Site Designer if I remember well)

**Comment by AndersB92** [comment]
I tried some of the other tools in PyRevitMEP - one of them work, others like 3D Rotate and Change Level don't. The one that work is the ConnectoTo.

I tried deactivitating (took a backup of both Addins folders of 2019, and deleted everything else in them, leaving only the pyRevit.addin. I startet a new mechanical project (with the default mechanical template) - created a simple circular duct setup, much like your video, and went through the 3D Rotate tool, and the same exact error/crash occured.
![image](https://user-images.githubusercontent.com/47623505/53343124-dd345d80-390f-11e9-9b68-256ccf398d92.png)

I deleted everything in the Addin folder including the Autodesk ones. It seems like the problem occurs with tools, that has an external window pop-up. Could that be the case?

**Comment by CyrilWaechter** [comment]
If all other tools except the 3 ones I told you works (Change Level, Rename and 3D Rotate) then yes it is related to external events (modeless windows).
Can you copy paste your pyRevit version and settings ? It will let me look the python engine you use and if rocket mode is activated.

**Comment by AndersB92** [comment]
Whoops - noticed the error message wasnt included in the print-screen, but it did occur.
Tried the same procedure in the 2018.1 edition of Revit aswell - same result. :/ I'll see about reinstalling Revit one of these upcoming days, and see if that could help.

**Comment by AndersB92** [comment]
Sure! Here's the pyRevit version:
![image](https://user-images.githubusercontent.com/47623505/53391691-735f9680-3997-11e9-8893-6292677ed434.png)

And here's the pyRevit Core settings (I can see that I have rocket mode activated):
![image](https://user-images.githubusercontent.com/47623505/53391617-3f847100-3997-11e9-868d-394d07bb0e10.png)

**Comment by CyrilWaechter** [comment]
I tried with rocket mode enabled, same ironpython engine, launched Revit under ENU (english) version and it still works here. I don't know what to say. Try disabling rocket mode just in case.

**Comment by AndersB92** [comment]
Succes! - Tried disabling rocket mode, and opened up a new default mech. template project in Revit 2019.2, and now it works flawlessly! :-) Works well in my current MEP project too.

**Comment by CyrilWaechter** [comment]
@eirannejad If you have any idea of what could cause rocket mode to fail on modeless windows scripts only on some PC I am taker.

**Comment by eirannejad** [comment]
Is this script part of pyRevitMEP? which one?

**Comment by CyrilWaechter** [comment]
Yes and any script using ExternalEvent apparently. But if you have no idea don't bother yourself with this it is the first case I encounter.

**Comment by shtirlitsDva** [comment]
Hi
I am also experiencing this issue (unrecoverable error on 3D rotate) on a freshly reinstalled computer and fresh Revit 19.2 install. It worked before reinstall and it works on a different computer (at work). Disabling Rocket Mode fixed this issue -- thanks to this thread.

**Comment by CyrilWaechter** [comment]
@shtirlitsDva Thanks for your feedback. I still don't know how to fix the issue as I am not able to reproduce it and have no idea of how to fix it except by disabling rocket mode.

Maybe it would worth to try to use the script with Ctrl-Shift-Alt-Click as described on [pyrevit docs](https://pyrevit.readthedocs.io/en/latest/articles/commandbutton.html?highlight=rocket%20mode) to see if it works.

@eirannejad This is something way over my head but as you succeed to use pythonnet to launch CPython scripts. Do you think there is a way to launch a script from an external window without using Revit API External Events ? Like something in pyRevit waiting for a command to run it in a valid Revit context.

**Comment by Milena001** [comment]
Hi,
I was also experiencing this issue with Change Level option. I tried to use this option and a message popped up: An unrecoverable error has occurred. The program will now be terminated. All of your data has been recently saved, so there is no need to create recovery files. 
After disabling Rocket Mode, Change Level works normal. Thanks for sharing this issue.
Revit version: 2017.2
pyRevit version: v4.6.24

**Comment by CyrilWaechter** [comment]
pyRevitMEP has been updated for pyRevit 4.7.4 #16 Please update and test. A new pyRevit feature may solve the rocket mode issue. Please also try with rocket mode reactivated.

**Comment by CyrilWaechter** [comment]
No answer for about a month. Considered as solved. Reopen it if necessary.
