### ISSUE TITLE
Change Level Issue

### ISSUE THREAD

**Issue by shtirlitsDva** [CyrilWaechter/pyRevitMEP#12]
Hi

Before, the Change Level tool kept the elements' position in space when changing the reference level, which was very useful, but now the element moves when this tool is used.

This happens for FamilyInstances.

I am working with MEP side of Revit, and changing ref level of Pipes does not move them in space, but fittings (FamilyInstances) move. This was not the case before.

**Comment by CyrilWaechter** [comment]
Hi,

I am not able to reproduce your error. It still works on my computers.

Please provide more information : 

- Revit version (including updates)
- pyRevit and engine used version (in about menu from pyRevit) eg
![image](https://user-images.githubusercontent.com/9622862/59497780-5db5a480-8e94-11e9-8bf6-37458f56628e.png)
- pyRevitMEP version (up to date for sure ? Sometimes pyRevit update fails)
- a minimal rvt file with only elements needed to reproduce the issue

**Comment by shtirlitsDva** [comment]
- Revit 2020
- pyRevit
![Version](https://user-images.githubusercontent.com/12258139/61206915-0b1a1300-a6f4-11e9-8e10-f06ca8bda573.png)
- pyRevitMEP
![MepVersion](https://user-images.githubusercontent.com/12258139/61206997-43215600-a6f4-11e9-8d5f-09d1650e0af6.png)
- Minimal rvt file: create a new project, draw a minimal pipe run with a fitting (elbow), try to change lvl of the fitting.
![ChgLvlBug](https://user-images.githubusercontent.com/12258139/61207218-d0fd4100-a6f4-11e9-8e54-846a31a9d703.gif)
As you can see in the attached gif, the fitting's level is changed, but the offset is calculated such as that the distance to previous level equals to distance that should be to the new level.
Something is wrong here:
![code](https://user-images.githubusercontent.com/12258139/61207400-4ec14c80-a6f5-11e9-9936-d16b520821f6.png)
But I cannot locate the issue by just looking at the code...

**Comment by shtirlitsDva** [comment]
I cannot see any recent changes in your code that should have affected the utility, so it must be a change in the Revit API 2020 that affects the function I think...

**Comment by CyrilWaechter** [comment]
Revit 2020 change. This is actually a good news. Fittings now behave like ducts when you change it's reference level it doesn't move !

**Comment by shtirlitsDva** [comment]
Wow, I've worked on 2020 for some months now and didn't notice this although I work with MEP things all the time. It is a good change for sure.

**Comment by RichardPinka** [comment]
Hello, back in this function again. If fittings were solved in 2020, still the duct accessories and air terminals are jumping with defined offset when i want to change their defailt level. 
I was hoping that Function Change level will change default level for air terminals and accessories in one click, but it does nothing. 
ideally, select all items (ducts, duct fittings, duct accessories, air terminals, including the duct insulation) and change it at one click at all 
![image](https://github.com/user-attachments/assets/06238a61-10ac-4f8b-ba51-d7798027d0bc)
air terminals and accessories jump over a floor when i setup different level.. : 
<img width="266" alt="revit_posun elementů 4" src="https://github.com/user-attachments/assets/f6501475-8cf2-4e77-b7e3-e7d42ab8c68c">

**Comment by CyrilWaechter** [comment]
@RichardPinka I have no issue here with air terminal and duct accessories. Can you provide a step by step way to reproduce your issue and your pyrevit|Revit information ? An ultra light test model with only elements you get an issue with might be good too.
