### ISSUE TITLE
Change Level Crash - Revit 2019

### ISSUE THREAD

**Issue by bullfrog4d** [CyrilWaechter/pyRevitMEP#14]
When initiating this tool I get a crash in Revit 2019.2.10.7 before I even select the item.  
Any advice?

**Comment by CyrilWaechter** [comment]
Hi,

Is pyRevit up to date ?
Is pyRevitMEP up to date ?
Have you tried to deactivate rocket mode in settings ?

Please share your pyRevit about screen (as the one below) :
![](https://user-images.githubusercontent.com/9622862/60579575-a968b900-9d83-11e9-9562-b26517d6ca29.png)

**Comment by bullfrog4d** [comment]
V4.6.23
No I have not deactivated rocket mode.

![image](https://user-images.githubusercontent.com/43181066/66145100-b8a01280-e5cf-11e9-9e2f-427623c2f995.png)

**Comment by bullfrog4d** [comment]
![image](https://user-images.githubusercontent.com/43181066/66145218-00bf3500-e5d0-11e9-9e0f-d7b69aa65c2e.png)

**Comment by CyrilWaechter** [comment]
Please : 
1. Update pyRevit
2. Try to use IronPython 2.7.9 engine instead of 2.7.7
3. Try with rocket mode deactivated

Tell me if something (and what) worked.

**Comment by bullfrog4d** [comment]
I reloaded IronPython to 2.7.9 but it still shows 2.7.7. 
Do I need to update some .net files?

**Comment by bullfrog4d** [comment]
![image](https://user-images.githubusercontent.com/43181066/66159315-5b1abe80-e5ed-11e9-9eb5-80ce22f4819c.png)

**Comment by CuongVTC** [comment]
@CyrilWaechter 
I have an error with this tool
![image](https://user-images.githubusercontent.com/19700387/66837684-97570300-ef8d-11e9-989d-4b9ac8dca3dc.png)
![image](https://user-images.githubusercontent.com/19700387/66837702-9f16a780-ef8d-11e9-83e6-1de61078a4dc.png)

**Comment by RagveN** [comment]
Hi Cyril,
I had a crash too when changing level .
ANd this hehelped : https://github.com/CyrilWaechter/pyRevitMEP/issues/14#issuecomment-538019865
Thanks a lot for all the work yo do !!

**Comment by CyrilWaechter** [comment]
pyRevitMEP has been updated for pyRevit 4.7.4 #16 Please update and test.

**Comment by CyrilWaechter** [comment]
Considered as solved. Reopen it if necessary.
