### ISSUE TITLE
Shared Parameter File

### ISSUE THREAD

**Issue by foxy6800** [CyrilWaechter/pyRevitMEP#15]
Hi,
I used "create a new empty definition file (standard revit shared parameter file) and then used save parameters to definition file. Every work fine and when i open the text file everything looks good.
When i try to use this definition file to bring in some of the shared parameters to a new projects, nothing is showing up. I don't get any error regarding the file, but no parameter shows. I have tried using revit and also Load from definition file in your tool !!!!
Could you please share the codes that write the parameters to the definitions file, so i could have a look. Thanks

**Comment by CyrilWaechter** [comment]
Hi,

This tool has been enhanced long time ago but I was waiting for pyRevit repo to update [rsparam](https://github.com/eirannejad/rsparam). I sent a [pull request in july](https://github.com/eirannejad/pyRevit/pull/643) but unfortunately it has been merged only in pyRevit 4.7 beta not in master.

Make sure that pyRevit and pyRevitMEP are up to date. Please copy paste pyRevit version (pyRevit menu -> About) as well as pyRevitMEP version (pyRevit dropdown -> settings -> extensions).

Libs related to parameters are stored in [this folder](https://github.com/CyrilWaechter/pyRevitMEP/tree/master/lib/pyrevitmep/parameter).

**Comment by foxy6800** [comment]
I have PyRevit V4.6.24, PyRevitMEP can't see any version :(

**Comment by CyrilWaechter** [comment]
#16 Please update and test.

**Comment by foxy6800** [comment]
Hello and Thanks for update
All the shared parameters tools have disappeared from pyRevitMEP.

**Comment by CyrilWaechter** [comment]
Please make sure you are running pyRevit last version which is 4.7.4 : 
![image](https://user-images.githubusercontent.com/9622862/69260622-7a32d700-0bc0-11ea-899b-df358f15f78c.png)
If pyRevit does not update using the update button you need to reinstall it.
This is what you are supposed to see :
![image](https://user-images.githubusercontent.com/9622862/69260513-4fe11980-0bc0-11ea-940b-47cc9202aa37.png)

**Comment by CyrilWaechter** [comment]
No answer for about a month. Considered as solved. Reopen it if necessary.
