### ISSUE TITLE
Exception: No module named revitutils

### ISSUE THREAD

**Issue by A2000J** [CyrilWaechter/pyRevitMEP#17]
Hi,
I tried the code from [here](https://pythoncvc.net/?p=255&unapproved=17203&moderation-hash=944926190b8604b1c0df7b6d67e6bbc5#comment-17203) but I got an exception.

My installed Versions
Revit: 19.2.10.7
pyRevit: 4.7.4

What I did:
1. Saved the code from [here](https://pythoncvc.net/?p=255&unapproved=17203&moderation-hash=944926190b8604b1c0df7b6d67e6bbc5#comment-17203) to a file.
2. Open a Revit project
3. Open the saved code from **Revit -> Add-Ins -> Interactive Python Shell -> Open Python Script**
4. Run the Script

The Result is:
> IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (64-bit)
> Type "help", "copyright", "credits" or "license" for more information.
> >>> 
> Exception : IronPython.Runtime.Exceptions.ImportException: No module named revitutils
>    bei Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
>    bei Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
>    bei Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
>    bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>    bei Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
>    bei IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
>    bei Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
>    bei Microsoft.Scripting.Hosting.ScriptSource.ExecuteAndWrap(ScriptScope scope, ObjectHandle& exception)
> >>> 

I need to mention, that I have few experience with Revit and Python. I usually work in AutoCAD or Inventor with .NET.
What have I done wrong.

Regards, Andreas

**Comment by CyrilWaechter** [comment]
Hi Andreas,
As stated in the article :
> Full source code with comments (**designed to be used in pyRevit**) :

So it has never worked in Revit Python Shell (RPS). To make it works in RPS you need to [sys.path.append](https://stackoverflow.com/questions/13829526/python-sys-path-appending-pythonpath) pyRevit libraries location.

However revitutils don't exist anymore. It has been replaced. Check pyRevitMEP source code for [https://github.com/CyrilWaechter/pyRevitMEP/blob/master/pyRevitMEP.tab/Modify.panel/Element3DRotation.pushbutton/script.py](Element3DRotation).
