### ISSUE TITLE
Revit does not delete selected Elements when "ModelessForm" Script is run

### ISSUE THREAD

**Issue by tillbaum** [CyrilWaechter/pyRevitMEP#19]
When elements are selected and "Delete Button" is pressend nothing happens. 

If I put an print "something" statement in the Execute method, 
just before the self.dothis() function call nothing happens too.

editnr1:
REvit version 2019
latest pyrevit version, 4.7.4
latest extensions. latest pyrevitMEP extension.

The External Event_delete Sample_script  works. Meaning. The Execute Method is fired. 
selected objects are deleted.

edit nr2:
The ExternalEvent_delete Sample_script does not work either: 

When you comment out the last line.  
"ExternalEventMy.Execute(handler_event, uidoc)", (which should not be needed.)

When the event is raised: exEvent.Raise()  the Execute method of the ExternalEventMy class
should fire. But it doesn't. 

When you copy and paste the whole code (except the last line) in to RPS, after exiting the RPS.
selected objectts are deleted ---> Execute method is invoked. Selected objects are deleted.  

The external Event.Raise() does not work, when starting the script from a button in pyrevit. 
 
When you do this with C# in an Revit Macro this works. 
See the youtube vid: 5 Secrets of Revit API coding. 
But I haven't figuered everything out yet.

Thank you very much for your script though. huge Inspiration.

**Comment by CyrilWaechter** [comment]
Hi,
I'll take a look later but please fill the bug report template, especially concerning Revit/pyRevit/engine/pyRevitMEP etc… versions.
You are talking about the delete button «hidden» under the sample drop-down right ?

**Comment by tillbaum** [comment]
Yes of course, sorry. 
I did. Thank You Cyril.

**Comment by CyrilWaechter** [comment]
On my side it is fixed. Please try.

External events are a pain to code (tend to crash if you do anything wrong) but great to use.
Also you should check [event.py](https://github.com/CyrilWaechter/pyRevitMEP/blob/master/lib/pyrevitmep/event.py)
And how it used in my scripts, eg. [Element3DRotation](https://github.com/CyrilWaechter/pyRevitMEP/blob/master/pyRevitMEP.tab/Modify.panel/Element3DRotation.pushbutton/script.py)
If you have any solution to better it and/or prevent Revit to crash when you have an error in you code please tell me.

**Comment by tillbaum** [comment]
Realy? It does work on your machine? The ModelessForm_script works? 
Can you show me ? Can you make a youtube vid or load it up on git?
In the vid 5 Secrets to API Coding (C#). The basic Code - Layout/ Architecture is the same. 
But with Python ...... hm.

**Comment by CyrilWaechter** [comment]
Maybe my answer was not clear enough lol.
I did a commit to fix the issue : e51f510

Did you update? Your pyrevitmep version has the correct hash ? 

The Element3DRotation with the same principle on lbry : 
[![Video on YouTube](http://img.youtube.com/vi/60Y_DJbIL5Y/0.jpg)](https://open.lbry.com/@CyrilWaechter:9/revit-api-3d-rotate-script-for-pyrevit)
Same on YouTube : 
<a href="http://www.youtube.com/watch?feature=player_embedded&v=60Y_DJbIL5Y
" target="_blank"><img src="http://img.youtube.com/vi/60Y_DJbIL5Y/0.jpg" 
alt="Same on youtube" width="240" height="180" border="10" /></a>

**Comment by tillbaum** [comment]
Awesome tool.  
If I use the 3D Rotate tool my Revit Application crashes with this Error Message. 
![grafik](https://user-images.githubusercontent.com/37901539/72327349-2cfb4f00-36b1-11ea-8c9b-6ffe10b98e5a.png)

**Comment by CyrilWaechter** [comment]
Sorry to insist, but can you please double check that pyRevitMEP is really up to date ? pyRevit update tool fails really often.
Please post your : 

* pyRevit -> Settings -> About screenshot
* pyRevit -> Extensions screenshot in which the hash appears
If you are sure that you are up to date then try to deactivate rocket mode in pyRevit settings.

**Comment by tillbaum** [comment]
Yes, I am checking, Yes pyrevit update tool fails.

**Comment by tillbaum** [comment]
The ModelessForm-tool works now, Wow! I am speechless. Thank you so much.
But the code did not change, I am comparing.

**Comment by CyrilWaechter** [comment]
You can check commit diff to see which change I made. Happy that it also works for you.
I close the issue. Reopen it if necessary.

**Comment by tillbaum** [comment]
Thanks so much!

**Comment by tillbaum** [comment]
One question: The Element3D Rotation-Tool. 
What kind of objects can be Rotated! Which category? 
All generic model types. (and everything derived from that) 
with the family parameter "always keep vertical " disabled?

**Comment by CyrilWaechter** [comment]
You can rotate pipes, ducts, air terminals, duct/pipe accessories and more…
You cannot rotate lighting fixtures, walls and some others…
I don't remember very well but I don't think it is even related to the «always keep vertical» parameter. Some categories can be rotated some cannot. If you use the same object and only change category it will also change you ability to rotate or not.
You'll have to test yourself for categories that might interest you ^^

**Comment by tillbaum** [comment]
ok thx
