### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by eirannejad** [CyrilWaechter/pyRevitMEP#2]
Hi. I really appreciate if you could revise the docstrings to be more specific and exactly explain what the tool does and what conditions need to be set for the tool to work properly. For example on the `Rename Views` tools the user would want to know:
- What is the naming convention?
- If they need to select the views first?
- What happens if the view name already exists?
- Would the `Title of Sheet` property would also be affected?

**Comment by CyrilWaechter** [comment]
Are tools now clear enough ? I mean can I close this general issue in case it is mostly ok and you can then reopen new one for a specific tool which needs clarification ?
Also I will continue to post more videos which shows how tools works when they are ready.

**Comment by eirannejad** [comment]
I actually haven't tested them. They were my suggestions only. Feel free to close.
