### ISSUE TITLE
I am saving the Shared parameter times incorrectly

### ISSUE THREAD

**Issue by lcwewei** [CyrilWaechter/pyRevitMEP#22]
1. Go to 'Mange'
2. Click on 'SharedParameters'
3. Click icon 'Load form definition file'
4. check '标高'
5. check 'F1'
6 Click icon 'save parameters to definition file'
7 See error

**Versions (please complete the following information):**
 - Revit: [2018,chinese]
 - pyRevit: [4.7.4, __pyRevit__ ]
 - pyRevitMEP [aed4ff9, ]
- rocket mode activated : No
- ironpython engine : [eg. 2.7.7]
- cpython engine : [eg. 3.7.2]

**Additional context**
IronPython Traceback:
Traceback (most recent call last):
 File "D:\pyRevit-Master\extensions\PyRevitMEP.extension\pyRevitMEP.tab\Manage.panel\Parameters.stack3\ManageSharedParameter.pushbutton\script.py", line 12, in <module>
 File "D:\pyRevit-Master\extensions\PyRevitMEP.extension\lib\pyrevitmep\parameter\manageshared.py", line 224, in show_dialog
 File "D:\pyRevit-Master\extensions\PyRevitMEP.extension\lib\pyrevitmep\parameter\manageshared.py", line 95, in save_click
 File "D:\pyRevit-Master\extensions\PyRevitMEP.extension\lib\pyrevitmep\parameter\__init__.py", line 253, in delete_from_definition_file
UnicodeDecodeError: ('unknown', '\x00', 12, 13, '')

Script Executor Traceback:
System.Text.DecoderFallbackException: 无法将位于索引 12 处的字节 [00] 由指定的代码页转换为 Unicode。
 在 Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
在 Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
在 Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
在 IronPython.Compiler.PythonCallTargets.OriginalCallTarget3(PythonFunction function, Object arg0, Object arg1, Object arg2)
在 System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
在 IronPython.Compiler.Ast.CallExpression.Invoke2Instruction.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
在 IronPython.Compiler.PythonCallTargets.OriginalCallTarget3(PythonFunction function, Object arg0, Object arg1, Object arg2)
在 CallSite.Target(Closure , CallSite , Object , Object , RoutedEventArgs )
在 System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
在 _Scripting_(Object[] , Object , RoutedEventArgs )
在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
在 System.Windows.Controls.Primitives.ButtonBase.OnClick()
在 System.Windows.Controls.Button.OnClick()
在 System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
在 System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
在 System.Windows.Input.InputManager.ProcessStagingArea()
在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
在 System.Windows.Window.ShowHelper(Object booleanBox)
在 System.Windows.Window.ShowDialog()
在 Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
在 System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
在 Microsoft.Scripting.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
在 IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
在 IronPython.Runtime.Method.MethodBinding.SelfTarget(CallSite site, CodeContext context, Object target)
在 System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
在 Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
在 IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
在 PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
[建筑规划方案.txt](https://github.com/CyrilWaechter/pyRevitMEP/files/4285028/default.txt)

**Comment by CyrilWaechter** [comment]
Hi,

As you can see in [commit list](https://github.com/CyrilWaechter/pyRevitMEP/commits/master), the pyRevitMEP version you use (aed4ff9) is previous  c98e12c378b112f3fee1233f245d66098362e7e7 (Update to pyRevit 4.7.4 and use of rsparam) and is therefore not compatible with pyRevit 4.7.4.

Please update pyRevitMEP. If update fails, uninstall and reinstall pyRevitMEP from extensions manager.

**Comment by lcwewei** [comment]
I have updated pyrevit to d50f9e4, but the same error occurred

**Comment by CyrilWaechter** [comment]
I launched Revit in [simplified chinese](https://knowledge.autodesk.com/support/revit-products/troubleshooting/caas/CloudHelp/cloudhelp/2020/ENU/Revit-Installation/files/GUID-BD09C1B4-5520-475D-BE7E-773642EEBD6C-htm.html) and create a group called 标高 and F1 but I wasn’t able to reproduce your error following your steps. Can you provide me you shared parameter file ?

**Comment by lcwewei** [comment]
Thank you very much for your reply. I upload the Shared parameter file.
[建筑规划方案.txt](https://github.com/CyrilWaechter/pyRevitMEP/files/4328937/default.txt)

**Comment by CyrilWaechter** [comment]
Now  I can reproduce it.

Some mess about character encoding apparently. Let me some time to see how I can fix this.

**Comment by lcwewei** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cyril Waechter"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 晚上6:03
收件人:&nbsp;"CyrilWaechter/pyRevitMEP"<pyRevitMEP@noreply.github.com&gt;;
抄送:&nbsp;"一个好人"<401247906@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CyrilWaechter/pyRevitMEP] I am saving the Shared parameter times incorrectly (#22)

Thank you very much for your reply. I have uploaded it

**Comment by CyrilWaechter** [comment]
Hi,
Issue is solved in dev branch. I wait pyRevit next release to push it.

**Comment by CyrilWaechter** [comment]
Done. Please try carefully and let me know if something else is going wrong.

**Comment by lcwewei** [comment]
There is now a new problem with the following error when deleting parameters

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\Administrator\AppData\Roaming\pyRevit\Extensions\PyRevitMEP.extension\pyRevitMEP.tab\Manage.panel\Parameters.stack\ManageSharedParameter.pushbutton\script.py", line 12, in <module>
 File "C:\Users\Administrator\AppData\Roaming\pyRevit\Extensions\PyRevitMEP.extension\lib\pyrevitmep\parameter\manageshared.py", line 266, in show_dialog
 File "C:\Users\Administrator\AppData\Roaming\pyRevit\Extensions\PyRevitMEP.extension\lib\pyrevitmep\parameter\manageshared.py", line 131, in delete_click
 File "C:\Users\Administrator\AppData\Roaming\pyRevit\Extensions\PyRevitMEP.extension\lib\pyrevitmep\parameter\__init__.py", line 304, in delete_from_definition_file
 File "D:\pyRevit-Master\pyrevitlib\rsparam\__init__.py", line 160, in get_params
 File "D:\pyRevit-Master\pyrevitlib\rsparam\__init__.py", line 91, in read_entries
 File "codecs.py", line 898, in open
TypeError: expected str, got DefinitionFile

Script Executor Traceback:
Microsoft.Scripting.ArgumentTypeException: expected str, got DefinitionFile
在 Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
在 Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
在 Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
在 Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
在 IronPython.Compiler.PythonCallTargets.OriginalCallTarget3(PythonFunction function, Object arg0, Object arg1, Object arg2)
在 System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
在 IronPython.Compiler.Ast.CallExpression.Invoke2Instruction.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
在 IronPython.Compiler.PythonCallTargets.OriginalCallTarget3(PythonFunction function, Object arg0, Object arg1, Object arg2)
在 CallSite.Target(Closure , CallSite , Object , Object , RoutedEventArgs )
在 System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
在 _Scripting_(Object[] , Object , RoutedEventArgs )
在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
在 System.Windows.Controls.Primitives.ButtonBase.OnClick()
在 System.Windows.Controls.Button.OnClick()
在 System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
在 System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
在 System.Windows.Input.InputManager.ProcessStagingArea()
在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
在 System.Windows.Window.ShowHelper(Object booleanBox)
在 System.Windows.Window.ShowDialog()
在 Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
在 System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
在 Microsoft.Scripting.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
在 IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
在 IronPython.Runtime.Method.MethodBinding.SelfTarget(CallSite site, CodeContext context, Object target)
在 System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
在 Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
在 Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
在 IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
在 PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by lcwewei** [comment]
And when the second click to delete the parameter, revit crashed

**Comment by CyrilWaechter** [comment]
Hello @lcwewei,

I am really sorry that it took me so long to fix this one…
