### ISSUE TITLE
[BUG] Change Level doesn't work with Air Terminals, Mechanical Equipment and Plumbing Fixtures

### ISSUE THREAD

**Issue by LostinBIM** [CyrilWaechter/pyRevitMEP#24]
**Describe the bug**
Hi! It seems that pyRevitMEP's Change Level function doesn't keep the objects in place. Some stay in place already by default in Revit but at least the categories listed in the title still change their elevation when changing the level.

The behavior of MEP objects has changed in some of the latest Revit updates when changing their level and it seems that also some of our Dynamo scripts that are supposed to solve the same problem have become "broken" in these newer versions. Not that those Dynamo scripts are of your concern, but I'm trying to give guesses about the underlying problem.

**To Reproduce**

Trying to change the level of any object that belongs to the listed categories moves it (or tries to move it and gives error if the network can't cope with it) according to the difference in level height.

**Expected behavior**
I suppose the objects would be expected to stay in the same elevation when using pyRevitMEP's Change Level function.

**Versions (please complete the following information):**
 - Revit: 2020.2
 - pyRevit: 4.8.4
 - pyRevitMEP 3df8e78
- rocket mode activated : Yes
- ironpython engine : 2.7.7
- cpython engine : 3.8.5 (pyRevit's About page reports "0", but in Core Settings it's listed as 385)

**Comment by CyrilWaechter** [comment]
Thanks a lot for your bug report. I am currently working more on Blender than Revit but I will get back to you when I'll go back to Revit.

**Comment by nnevynn** [comment]
I'm having the exact same problem on Revit 2021. The best function in pyRevitMEP, sadly it does not work anymore. :(

**Comment by CyrilWaechter** [comment]
Sorry that it took so long to fix… Thanks @nnevynn for remembering me this issue.

I reworked the code to make easy to add new categories if needed.

I do not have Revit 2019 and below anymore.  If one of you can ensure that it still works with Revit <= 2019 it would be great.

**Comment by nnevynn** [comment]
I was not that quick to get back to you. 

A few days ago I had to do a clean re-install of my computer. So now with a clean installed version of Revit 2021 and pyRevit MEP the "Change Revit" seams to work as expected. 

This is a bit weird but good news :)
