### ISSUE TITLE
Element3D rotation function [BUG]

### ISSUE THREAD

**Issue by RichardPinka** [CyrilWaechter/pyRevitMEP#28]
**Describe the bug**
Hello Cyril, 
function 3d rotate does not work :(

**To Reproduce**
1. I marked one duct elbow 90° with duct on it i wanted to rotate.
2. I clicked "3d rotate" function.
3. See error  [log_0]

**Expected behavior**
I should rotate duct elements

**Screenshots**
![image](https://user-images.githubusercontent.com/8267708/180449646-ee6e0841-efaa-4ed7-b203-3c2abf4f3ed0.png)

**Versions (please complete the following information):**
 - Revit:   2022.1
 - pyRevit: 4.8.10.22040   ( dropdown -> __About__ and take a screenshot => when i click ABOUT. it shows me some error  [log_1]
 - pyRevitMEP : probably 1.3.15.1010 ...     dropdown-extensioins .. does not work.. it shows me some errror log [log_2]
- rocket mode activated : Yes/No   => i do not really know
- ironpython engine : [eg. 2.7.7] => i do not really know how to find this out
- cpython engine : [eg. 3.7.2] => i do not really know how to find this out

**Additional context**
sorry to show you it is not working  :(

logs attached for download here:
[pyRevitMEP.zip](https://github.com/CyrilWaechter/pyRevitMEP/files/9168161/pyRevitMEP.zip)

**Comment by CyrilWaechter** [comment]
Hello @RichardPinka,

Sorry for this late answer I am awfully overflowed.

Many of the issues you get are apparently not related to this script (error when pressing about or extension for example). I suggest that you reinstall pyRevit.

**Comment by CyrilWaechter** [comment]
@RichardPinka Any news ?

**Comment by RichardPinka** [comment]
Hello Cyril, sorry for delayed answer, I was quite busy with finishing some larger hvac desings.. 
well, yes, after reinstallation the function seems working => the version "rotate around selected axis" .. yes
when i try to use function "Rotate on itself"  .. sometimes it worked (in some mechanical equpiment - FAN for circular ducts, air terminals)
sometimes not : (when i want to rotate ducts, or in some situation when i select mechanical equpiment - split interior unit)
end error messages occur:
![image](https://user-images.githubusercontent.com/8267708/232234108-bd3d29b9-62bc-4530-a0a3-d9a8b9232e08.png)
![image](https://user-images.githubusercontent.com/8267708/232234220-3908af3f-ea69-4802-af94-963be38afcc9.png)

but important is the first function which seems to work.  so thank you.  

It was for me good to get make install the pyRevit MEP just automatically within pyRevit plugin (i remember the manual way of installation was sotly killing me. )

**Comment by CyrilWaechter** [comment]
Hello @RichardPinka 
Rotate around itself is not designed to work for ducts/pipes. What are the use-cases ?
About mechanical equipment do you have a sample ?
