### ISSUE TITLE
[BUG] Crash on Family Parameter commit (workaround included)

### ISSUE THREAD

**Issue by gtabaka** [CyrilWaechter/pyRevitMEP#29]
**Describe the bug**
Family Parameter editor crashes when attempting to commit new family parameters, whether from Shared Parameters or Family parameters. (Code workaround included)

**To Reproduce**
1. Go to 'Manage Project Parameters'
2. Create a parameter (or import from shared parameter file)
3. Click the checkmark. This results in a log window error.
4. Clicking checkmark again will crash Revit.

**Expected behavior**
Expected parameter to be added to the family and be accessible in native RVT tools.

**Screenshots**
Not included

**Versions (please complete the following information):**
 - Revit: 2022.0.2.392
 - pyRevit: 4.8.12
 - pyRevitMEP afec142
- rocket mode activated : Yes
- ironpython engine : 2.7.7
- cpython engine : 3.8.5

**Additional context**
The problem is in managefamily.py, near line 105. pyRevitMEP is attempting to determine if the Shared Parameter file is in Unicode or UTF-8 encoding, but the pyRevit function in coreutils.check_revittxt_encoding() is no longer present in 4.8.12 (or maybe earlier). Temporary workaround: My Shared Parameter file was Unicode-encoded so edit %Appdata%\pyRevit\Extensions\PyRevitMEP.extension\lib\pyrevitmep\parameter\managefamily.py near line 103:

1) Comment out the if..else
        #if script.coreutils.check_revittxt_encoding(src_file):
        #    encoding = "utf_16_le"
        #else:
        #    encoding = "utf_8"
2) Insert at the same level of tab indentation
        encoding = "utf_16_le"    # or "utf-8" if yours is that encoding. Doing this without knowing will corrupt your shared parameters file, so make a backup.
3) Save file, disable pyRevitMEP and re-enable into pyRevit

**Comment by CyrilWaechter** [comment]
Hello @gtabaka,

So sorry for such a late fix. Thanks a lot for your report and fix hint !

**Comment by gtabaka** [comment]
Thank you for making the fix and for contributing to the open source and Revit communities.

Greg Tabaka, PE

Principal

ANTINOMY

---------------------------------------------------------------

---------------------------------------------------------------

---------------------------------------------------------------

Antinomy Consulting Engineers

600 Rinehart Road, Suite 2054, Lake Mary, FL 32746‑4955

Phone [321-888-2882×1000](tel:+132188828821000) Mobile [321-501-1050](tel:3215011050)

Email ***@***.*** Web [antinomy.com](https://www.antinomy.com) [Send Files](https://toolbox.antinomy.com/index.php/s/ZBAkFPiqDM6C852)

Sent from Proton Mail mobile

-------- Original Message --------
