### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by farid274** [CyrilWaechter/pyRevitMEP#30]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Revit: [e.g. 2020.2]
 - pyRevit: [e.g. 4.7.4, __pyRevit__ dropdown -> __About__ and take a screenshot]
 - pyRevitMEP [e.g. c98e12c, __pyRevit__ dropdown -> __Extensions__ -> __Last commit__ column (this is the hash of the last commit)]
- rocket mode activated : Yes/No
- ironpython engine : [eg. 2.7.7]
- cpython engine : [eg. 3.7.2]

**Additional context**

**Comment by CyrilWaechter** [comment]
Was it a test or something went wrong because description is not filled (default text)
