### ISSUE TITLE
CreateSectionFrom is using "Prefix" only  first time[BUG]

### ISSUE THREAD

**Issue by heinrichboldt** [CyrilWaechter/pyRevitMEP#31]
I tried to use the fuction, was on search for that for long time. 

was confused to see for the first Section created with "Mur None" as name, next section was named "Section 1" and ongoing. I dont know, if this is a bug or only missunderstanding about the functions. 

also confusing is, that there is no description, to first select the elements, than go to "CreateSectionFrom"

**To Reproduce**
1. start with nosections in project
2. create walls
3. select walls
4. "CreateSectionFrom"
5. see first section named " Mur None"
6. second section is "Section 1"
7. when doing something different or changing the "Prefix" it will create the following Section with the new prefix and will continue with others with "Section * "

**Expected behavior**

![image](https://user-images.githubusercontent.com/7993879/214498892-24989ded-521d-4fa1-9989-177705ff03f0.png)

**Versions (please complete the following information):**
 - Revit:2020.2.9
 - pyRevit: ![image](https://user-images.githubusercontent.com/7993879/214499453-c5fdf3d2-2572-45fd-b364-b47062e03f6c.png)
 - pyRevitMEP ![image](https://user-images.githubusercontent.com/7993879/214499525-b43dec17-f3b6-407d-b672-8929757eb4d0.png)
- rocket mode activated : Yes
- ironpython engine :  2.7.7
- cpython engine : 3.8.5

**Comment by CyrilWaechter** [comment]
Hi @heinrichboldt,

Thanks for your report. It is now fixed. For info section name was designed to concatenate prefix + Mark parameter value.
