### ISSUE TITLE
usage of RoomToSpace [BUG]

### ISSUE THREAD

**Issue by RichardPinka** [CyrilWaechter/pyRevitMEP#35]
**Describe the bug**

I tryied to use fucnction RoomToSpace   for the first time. But there is no manual for it. How to use ? 
Do you have to copy rooms to your own model and create spaces before use this function ? 
Or You have to create just spaces and function will suck data from rooms from linked model ? 
Or does function do all above mentioned on its own ? 

do I have to have selected Rooms before application of functions ?  or do i have to have selected spaces ? 
or do i have to have selected both - spaces + rooms before application function  ? 

ot of questions arise when the error window occurs and user sipmly is not sure if he did not use the proper way 

**To Reproduce**
1. no matter the questions above, i tried to copy rooms from linked model to my model and ad afterwards i created the spaces (only on one level from more leveled model-building). 
2. I clicked RoomToSpace function
3. error occured

**Expected behavior**
room data from rooms would be copied to spaces

**Screenshots**
error : 
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\Richard_dell\AppData\Roaming\pyRevit\Extensions\PyRevitMEP.extension\pyRevitMEP.tab\Data.panel\RoomToSpace.pushbutton\script.py", line 154, in <module>
 File "C:\Users\Richard_dell\AppData\Roaming\pyRevit\Extensions\PyRevitMEP.extension\pyRevitMEP.tab\Data.panel\RoomToSpace.pushbutton\script.py", line 33, in __init__
TypeError: 'DocumentSet' object is not subscriptable

Script Executor Traceback:
IronPython.Runtime.Exceptions.TypeErrorException: 'DocumentSet' object is not subscriptable
 at Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx)
 at Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
 at IronPython.Runtime.Types.LateBoundInitBinder.FastInitSite`1.CallTarget(CallSite site, CodeContext context, Object inst, T0 arg0)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at IronPython.Runtime.Types.PythonType.FastTypeSite`1.CallTarget(CallSite site, CodeContext context, Object type, T0 arg0)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Versions (please complete the following information):**
 - Revit: 2022.1
 - pyRevit: [e.g. 4.7.4, __pyRevit__ dropdown -> __About__ and take a screenshot]
 - 
![image](https://github.com/CyrilWaechter/pyRevitMEP/assets/8267708/e72aeacd-7311-427e-8b44-4fc94f62c808)

 - pyRevitMEP [e.g. c98e12c, __pyRevit__ dropdown -> __Extensions__ -> __Last commit__ column (this is the hash of the last commit)]
92d9398

- rocket mode activated : Yes

- ironpython engine : 2.7.7
- cpython engine :  3.8.5

**Additional context**

**Comment by RichardPinka** [comment]
Hello, tested on Revit 2024.  
I opened RoomToSpace function window. 
I did set source attached model, set my target model where i have "new" spaces. 
I did set parameters to copy from rooms of source model to spaces onto my target model . 
..i clicked OK. 
nothing happened :(
I wish this would be repaired
![image](https://github.com/user-attachments/assets/60c545b1-64a1-4924-942a-7ffe9f75f1aa)

**Comment by CyrilWaechter** [comment]
This function would require some better explanations… You actually need to use actual parameter names in your own language. It still require more polish but I confirm it works on Revit 2024.

Little first improvements over here: [e5bd72c](https://github.com/CyrilWaechter/pyRevitMEP/commit/e5bd72c0da756acf5af462351c4f9644f44d8a50)

**Comment by CyrilWaechter** [comment]
Hello @RichardPinka,
I see the issue in your input. The example fouled you. The «%» sign should not be place before the parameter name or separator. Please update pyRevitMEP and try with following in `Snowdown Towers Sample HVAC`:
Source input:
```
Number	-	Name
n°	Number	| name: 	Name
```
Target:
```
Comments
Name
```
You should see it working as expected.

I hope usage will be more clear now.

**Comment by RichardPinka** [comment]
Hello Cyril, Finally, i undrerstood how should i use this.. unfortunatelly, description and for me useless «%» sign gave me just confusion, to be honest. 
OK, in the "test model"  that function works, perfect. 
Unfortunatelly, in real-life model, which i am actually work with, it is not working. It seems more complicated.. why ?  I am not sure to be honest. 
But i know, there is important to know from where revit shows the "alternative" parameters of attached model´s room data (e.g. name, number) ... i see in my situation that data from where my space sucks data from are "unnocupied" (second picture below)
but actual room data are in different model (first picture). 
Architects created models topology like this, and all of it is part of the room geometry creation of rooms created in one of the models below :
- structural models - made for static - structural designer
     - contains floors, columns, walls made from contcrete- structural elements
- facade -defining the envelope of building
      - shapes some of the rooms 
- architectural - contains some internal walls AND the final rooms. in this model are joined the models above (with room bounding:ON, as an OVERLAY models)  .. i have attached this model for copying data from rooms to spaces in my hvac model. 

<img width="1049" alt="1" src="https://github.com/user-attachments/assets/e74828d2-78bb-4b53-8da9-531567afe87b">


<img width="1067" alt="2" src="https://github.com/user-attachments/assets/596502f0-6c82-4b75-a061-932ea63d5816">

... NEITHER setting of all sub-attached models into attached models to "ATTACHMENT" instead of "OVERLAY" did not help

**Comment by RichardPinka** [comment]
Hello @CyrilWaechter , I am testing the function on different model, where not three but just two models of building i do attach to my hvac model. (these are architectural and structural model). 
There was partially success. I was able to copy data from ordinary attribute "Name" "Number" (hurray!) but, 
newly created attribute "Označení bytu"  (flat mark) cannot be copied to some ordinary attribute, e.g. "Comments"
![image](https://github.com/user-attachments/assets/11eb524f-de2f-48bf-8636-9e3d88b37e51)

also, haven´t been able to paste data to newly created my own parameters such "ID_PRVKU" or "OBECNÝ KOMENTÁŘ"
![image](https://github.com/user-attachments/assets/63149ae6-b832-42c1-a6f7-88c16848003a)
![image](https://github.com/user-attachments/assets/4b493e48-93e3-4867-9a86-37c4f23b2751)

you may see their existence in my model here:
![image](https://github.com/user-attachments/assets/18f62a0f-577c-487d-bffe-900ecb16ad10)

**Comment by CyrilWaechter** [comment]
Hello @RichardPinka,

About your first reply:
- script takes your space base point and look if there is a room at this location if the selected model (see: [GetRoomAtPoint](https://www.revitapidocs.com/2022/656d34c2-1e53-7278-ab83-fefaff7f40a4.htm))
- if room is found it pull data from it

In your case I do not see any reason to not be able to find the room. You can send me your models by email for privacy (use [swisstransfer](https://www.swisstransfer.com) or something like that).

About your second answer it is probably a character encoding issue as [TextBox.Text](https://learn.microsoft.com/fr-fr/dotnet/api/system.windows.controls.textbox) is UTF-16 and the rest is utf-8. I found a way to avoid this issue (see: https://github.com/CyrilWaechter/pyRevitMEP/commit/cb97cf4bdca32fd8145f8e7e10859e852c20a459). Please update pyRevitMEP.

**Comment by CyrilWaechter** [comment]
Fixed in https://github.com/CyrilWaechter/pyRevitMEP/commit/42f98bd1d88a53b3ad109a866f886dcaf9c829e6
