### ISSUE TITLE
error for a missing excel icon

### ISSUE THREAD

**Issue by Thomas84** [CyrilWaechter/pyRevitMEP#5]
I get an error for a missing excel icon =)

INFO: [Reload] Reloading.... 

INFO: [pyrevit.loader.sessioninfo] pyRevit version: 4.4:08a3297 -  with  in Portland, OR 

INFO: [pyrevit.loader.sessioninfo] Host is Autodesk Revit 2018 (build: 20170927_1515(x64) id: 6272) 

INFO: [pyrevit.loader.sessioninfo] Running on: 2.7.7 (IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (64-bit)) 

INFO: [pyrevit.loader.sessioninfo] Home Directory is: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit 

INFO: [pyrevit.loader.sessioninfo] Session uuid is: c7d20ddc-0812-11e8-95cb-7da2546aeb90 

INFO: [pyrevit.loader.sessioninfo] Base assembly is: pyRevit_2018_27e577b999513998_PyRevitBaseClasses 

INFO: [pyrevit.loader.sessioninfo] Config file is: C:/Users/tvogt/AppData/Roaming/pyRevit/pyRevit_config.ini 

INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly loaded from cache: pyApex 

INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly loaded from cache: pyRevitCore 

INFO: [pyrevit.extensions.extensionmgr] Skipping disabled ui extension: pyRevitDevTools 

INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly loaded from cache: PyRevitMEP 

INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly loaded from cache: PyRevitPlus 

INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly loaded from cache: pyRevitTools 

INFO: [pyrevit.extensions.extensionmgr] Skipping disabled ui extension: pyRevitTutor 

INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly parsed: rvt_fixme 

INFO: [pyrevit.extensions.extensionmgr] Updating cache for ui_extension: rvt_fixme 

INFO: [pyrevit.loader.sessionmgr] Extension assembly created: pyApex 

INFO: [pyrevit.loader.sessionmgr] UI created for extension: pyApex 

INFO: [pyrevit.loader.sessionmgr] Extension assembly created: pyRevitCore 

INFO: [pyrevit.loader.sessionmgr] UI created for extension: pyRevitCore 

INFO: [pyrevit.loader.sessionmgr] Extension assembly created: PyRevitMEP 

ERROR: [pyrevit.coreutils.ribbon] Error adding icon for Excel | Can not create icon from given file: None | Name: Excel RevitAPIObject: <Autodesk.Revit.UI.PushButton object at 0x000000000000073B [Autodesk.Revit.UI.PushButton]> 

Traceback: 
 File "C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/pyrevitlib/pyrevit/coreutils/ribbon.py", line 768, in create_push_button 
 existing_item.set_icon(icon_path, icon_size=ICON_LARGE) 

INFO: [pyrevit.loader.sessionmgr] UI created for extension: PyRevitMEP 

INFO: [pyrevit.loader.sessionmgr] Extension assembly created: PyRevitPlus 

INFO: [pyrevit.loader.sessionmgr] UI created for extension: PyRevitPlus 

INFO: [pyrevit.loader.sessionmgr] Extension assembly created: pyRevitTools 

INFO: [pyrevit.loader.sessionmgr] UI created for extension: pyRevitTools 

INFO: [pyrevit.loader.sessionmgr] Extension assembly created: rvt_fixme 

INFO: [pyrevit.loader.sessionmgr] Running startup tasks... 

INFO: [pyrevit.loader.sessionmgr] UI created for extension: rvt_fixme 

INFO: [pyrevit.loader.sessionmgr] Load time: 4.5554 seconds

**Comment by CyrilWaechter** [comment]
Hi Thomas,
Thanks for your message. I added an icon to this lab script called «excel»  8fec1d0
You should really upgrade to pyRevit 4.5 : http://pythoncvc.net/?p=386. pyRevitMEP is not keeping compatibility with pyRevit 4.4.
Can you please try to : 
1. Update pyRevit to version 4.5 (It is advised to uninstall 4.4)
2. Update pyRevitMEP
3. Try again and let met know if issue is solved

**Comment by Thomas84** [comment]
oh ok, my mistake, I have used the update button...
