### ISSUE TITLE
How To Manual install pyRevitMEP

### ISSUE THREAD

**Issue by dmscholten87** [CyrilWaechter/pyRevitMEP#6]
How can i manual pyRevitMEP on pyRevit?

I have clone pyRevitMEP from Github and place the map pyRevitMEP.tab in the extension map on C:/pyRevit/

But now i get the follow notification:
![image](https://user-images.githubusercontent.com/41347566/42871629-18e47368-8a7b-11e8-8854-faf62017ad63.png)

I think he's looking for the "lib" directory. This directory is in the clone from GitHub.
Must i place this on a specific directory?

Thanks for the effort

**Comment by CyrilWaechter** [comment]
Can you please check if you have a lib folder inside your pyRevitMEP.extension folder please ?
![image](https://user-images.githubusercontent.com/9622862/42886776-b2c7d334-8aa4-11e8-8429-92e54504f281.png)

**Comment by dmscholten87** [comment]
Thanks Cyril, this helps a lot. It works now good 👍

**Comment by CyrilWaechter** [comment]
Instructions added in 109d81d
Video created https://www.youtube.com/watch?v=z3GGYrsRrYI
