### ISSUE TITLE
setting projectparameters crash

### ISSUE THREAD

**Issue by epeter-** [CyrilWaechter/pyRevitMEP#7]
revit 2017, pyrevit latest update
workflow:
create shared parameters -> save
menu manage project parameters
select parameters from shared parameter file  (Button "I") (Button"[<-]) (Button "OK")
set values for 3 parameters of same group (all parameters are assigned to same classes)
click (Button"OK") or (Button"Save")
CRASH
error message:
![image](https://user-images.githubusercontent.com/6928491/46303647-ab130f80-c5ac-11e8-867a-fdeb7257d741.png)
![image](https://user-images.githubusercontent.com/6928491/46303680-c7af4780-c5ac-11e8-9958-ccbb63d136ad.png)

**Comment by CyrilWaechter** [comment]
Hi @epeter- ,
Thanks for catching this issue. It looks like I broke something someday. On my side it is solved. Please update pyRevitMEP and test it.

For info (I know ui is not very explicit yet) : 
I stand for instance parameter.
T stand for type parameter.

Please backup your definition file (shared parameter file) and save your project before using parameter management tools. I fear there is still some instabilities.
